name: System Tests
on: [push]
jobs:
  cypress:
    name: Cypress system tests
    runs-on: ubuntu-latest
    
    env:
      # SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      # SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      # PROJECT_ID: nnhiufnpncvtpbvwlgsc
    
    run: echo ${{ secrets.VITE_SUPABASE_URL }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    
      # run: npm install

    # - name: Supabase
    #   uses: supabase/setup-cli@v1
    #   with:
    #     version: 1.16.1

    - name: Cypress.io
      uses: cypress-io/github-action@v5.0.0
      with:
        build: npm run build
        start: npm run start-server

    # - name: Install Dependencies
    #   run: npm install 
    # - name: Run Tests
    #   run: npm run ci
    # https://www.youtube.com/watch?v=rOLyOsBR1Uc

    # https://stackoverflow.com/questions/60176044/how-do-i-use-an-env-file-with-github-actions
    
        
