name: System Tests
on: [push]
jobs:
  cypress:
    name: Cypress system tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    
    - name: Cypress.io
      uses: cypress-io/github-action@v5.0.0
      with:
        build: npm run build
        start: npm run start-server

    # - name: Install Dependencies
    #   run: npm install 
    # - name: Run Tests
    #   run: npm run ci
    
        
